version: '3'

services:
  app:
    image: fossbilling/fossbilling:latest
    container_name: fossbilling-app
    ports:
      - "8080:80"  
    volumes:
      - ./public:/var/www/fossbilling/public
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=fossbilling
      - DB_USER=fossbillinguser
      - DB_PASSWORD=password
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: fossbilling-db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=fossbilling
      - MYSQL_USER=fossbillinguser
      - MYSQL_PASSWORD=password
    volumes:
      - fossbilling-db-data:/var/lib/mysql

volumes:
  fossbilling-db-data:
