- name: Installer les dépendances système
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

- name: Installer runc (prérequis pour CRI-O)
  apt:
    name: runc
    state: present

- name: Activer et démarrer iscsid
  systemd:
    name: iscsid
    enabled: yes
    state: started

- name: Copier le script d'installation de CRI-O sur le worker
  ansible.builtin.copy:
    src: templates/crio_setup.sh
    dest: /tmp/crio_setup.sh
    mode: '0755'

- name: Exécuter le script d'installation CRI-O
  ansible.builtin.shell: /tmp/crio_setup.sh

- name: Mettre à jour le cache APT
  apt:
    update_cache: yes
    cache_valid_time: 3600


- name: Mettre à jour les paquets APT
  ansible.builtin.apt:
    update_cache: yes


- name: Installer CRI-O
  apt:
    name: cri-o
    state: present



- name: Créer le répertoire pour le lien symbolique runc
  file:
    path: /usr/lib/cri-o-runc/sbin
    state: directory
    mode: '0755'

- name: Créer lien symbolique pour runc
  file:
    src: /usr/bin/runc
    dest: /usr/lib/cri-o-runc/sbin/runc
    state: link
    force: yes

- name: Déployer la configuration CRI-O
  template:
    src:  templates/criotemplate.conf.j2 
    dest: /etc/crio/crio.conf
    mode: 0644

- name: Démarrer CRI-O
  systemd:
    name: crio
    enabled: yes
    state: started

- name: Installer crictl
  get_url:
    url: https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.33.0/crictl-v1.33.0-linux-amd64.tar.gz
    dest: /tmp/crictl.tar.gz

- name: Extraire crictl
  unarchive:
    src: /tmp/crictl.tar.gz
    dest: /usr/local/bin/
    remote_src: yes

- name: Rendre crictl exécutable
  file:
    path: /usr/local/bin/crictl
    mode: '0755'
    state: file

- name: Changer le propriétaire du socket CRI-O
  file:
    path: /var/run/crio/crio.sock
    owner: {{ ansible_user }}
    group: {{ ansible_user }}
    mode: '0660'

