- name: Apply OpenEBS
  command: kubectl apply -f https://openebs.github.io/charts/openebs-operator.yaml
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  become: yes
  become_user: "{{ ansible_user }}"
  
- name: Apply  JIRA openebs
  command: kubectl apply -f https://openebs.github.io/charts/jiva-operator.yaml
  environment:
    KUBECONFIG: /home/{{ ansible_user }}/.kube/config
  become: yes
  become_user: "{{ ansible_user }}"
  
