apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: clusterrolebinding-admin
subjects:
  - kind: ServiceAccount
    name: default  
    namespace: 3spfe 
roleRef:
  kind: ClusterRole
  name: cluster-admin  
  apiGroup: rbac.authorization.k8s.io

