---
- name: Configuration SSH et sudo automatisée
  hosts: all
  gather_facts: false

  tasks:
    # Génération de la clé SSH sur le master (dans ~/.ssh)
    - name: Générer clé SSH sur master si inexistante
      block:
        - name: Vérifier existence clé SSH
          stat:
            path: ~/.ssh/id_rsa
          register: key_check
          delegate_to: "{{ groups['master'][0] }}"

        - name: Créer répertoire .ssh
          file:
            path: ~/.ssh
            state: directory
            mode: '0700'
            owner: "{{ ansible_user }}"
          when: not key_check.stat.exists
          delegate_to: "{{ groups['master'][0] }}"

        - name: Générer clé RSA
          command: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -N ""
          args:
            creates: ~/.ssh/id_rsa
          when: not key_check.stat.exists
          delegate_to: "{{ groups['master'][0] }}"
      run_once: yes

    # Récupération et déploiement de la clé publique
    - name: Lire clé publique du master
      slurp:
        src: ~/.ssh/id_rsa.pub
      register: master_pub_key
      delegate_to: "{{ groups['master'][0] }}"
      run_once: yes

    - name: Déployer clé sur tous les nœuds
      authorized_key:
        user: "{{ ansible_user }}"
        key: "{{ master_pub_key.content | b64decode }}"
        manage_dir: yes
        path: ~/.ssh/authorized_keys

    # Configuration sudo sécurisée
    - name: Configurer sudo sans mot de passe
      become: yes
      copy:
        dest: /etc/sudoers.d/99_{{ ansible_user }}_nopasswd
        content: "{{ ansible_user }} ALL=(ALL) NOPASSWD:ALL"
        mode: '0440'
        validate: 'visudo -cf %s'


