apiVersion: v1
kind: Service
metadata:
  name: fossbilling-app
spec:
  type: {{ .Values.service.app.type }}
  selector:
    app: fossbilling-app
  ports:
    - port: {{ .Values.service.app.port }}
      targetPort: {{ .Values.service.app.targetPort }}
