kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  storage-cicd 
provisioner: jiva.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: "jiva"
  policy: "jiva-policy"













