apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-cicd
provisioner: jiva.csi.openebs.io  # Provisioner pour Jiva
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  cas-type: jiva  
  jiva.replicaCount: "2"  
  fsType: "ext4"
