---
apiVersion: v1
kind: Namespace
metadata:
  name: sonatype-registry
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nexus3-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /mnt/nexus3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexus3-pvc
  namespace: sonatype-registry
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nexus3-config
  namespace: sonatype-registry
data:
  nexus.properties: |
    nexus.scripts.allowCreation=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexus3
  namespace: sonatype-registry
  labels:
    app: nexus3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexus3
  template:
    metadata:
      labels:
        app: nexus3
    spec:
      securityContext:
        fsGroup: 200
      initContainers:
        - name: init-permissions
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /nexus-data/etc/logback && \
              chown -R 200:200 /nexus-data && \
              chmod -R 770 /nexus-data
          volumeMounts:
            - name: nexus3-data
              mountPath: /nexus-data
      containers:
        - name: nexus3
          image:  jbuncle/nexus-repository-composer
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: nexus3-data
              mountPath: /nexus-data
            - name: nexus3-config
              mountPath: /nexus-data/etc/nexus.properties
              subPath: nexus.properties
      volumes:
        - name: nexus3-data
          persistentVolumeClaim:
            claimName: nexus3-pvc
        - name: nexus3-config
          configMap:
            name: nexus3-config
---
apiVersion: v1
kind: Service
metadata:
  name: nexus3-service
  namespace: sonatype-registry
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32323
  selector:
    app: nexus3

