apiVersion: v1
kind: Namespace
metadata:
  name: testing
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storage-postgres
provisioner: jiva.csi.openebs.io
allowVolumeExpansion: true
parameters:
  cas-type: "jiva"
  policy: "jiva-policy"
  replicaCount: "2"
  storage: "10Gi"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: testing
spec:
  storageClassName: storage-postgres
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: testing
  labels:
    app: postgres
data:
  POSTGRES_DB: sonar_db
  POSTGRES_USER: sonar_user
  POSTGRES_PASSWORD: S0N4RQUB3
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  namespace: testing
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: testing
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        fsGroup: 1001
        runAsUser: 1001
      containers:
        - name: postgres
          image: bitnami/postgresql:16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "no"
            - name: PGDATA
              value: /bitnami/postgresql/data
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - name: postgres-data
              mountPath: /bitnami/postgresql
              subPath: pgdata
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 1Gi
              cpu: 500m
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc
