---
- name: Playbook principal pour configurer les outils CI/CD
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars/passwordvars.yml 
    - vars/sonarvars.yaml

  tasks:
    - name: Inclure les tâches de configuration Sonar
      include_tasks: "{{ deploy_path }}/deploy-ci-cd/sonarqubedeploy/configSonar.yml"

    - name: Inclure les tâches de configuration Nexus
      include_tasks: "{{ deploy_path }}/deploy-ci-cd/nexus/ConfigureNexus.yml"

    - name: Inclure les tâches de configuration Jenkins
      include_tasks: "{{ deploy_path }}/deploy-ci-cd/jenkins-conf/ConfigureJenkins.yml"
