---
- name: Déploiement complet CI/CD avec Jenkins, SonarQube, Nexus, PostgreSQL et installation de Trivy
  hosts: localhost 
  vars_files:
     - vars/passwordvars.yml 
  tasks:
   
    - name: Déployer Jenkins depuis jenkinsdeploy.yaml
      command: kubectl apply -f {{ deploy_path }}/deploy-ci-cd/jenkins-conf/jenkinsdeploy.yaml

    - name: Inclure les tâches de déploiement de PostgreSQL
      command: kubectl apply -f {{ deploy_path }}/deploy-ci-cd/sonarqubedeploy/postgres.yaml


    - name: Déployer SonarQube depuis sonar.yaml
      command: kubectl apply -f {{ deploy_path }}/deploy-ci-cd/sonarqubedeploy/sonar.yaml
     
    - name: Déployer Nexus depuis deplo_nexus.yaml
      command: kubectl apply -f {{ deploy_path }}/deploy-ci-cd/nexus/deplo_nexus.yaml

    - name: Inclure les tâches pour installer Trivy
      command: kubectl apply -f {{ deploy_path }}/deploy-ci-cd/security/DeployTrivy.yaml
 
    - name: Ajouter un délai de 60 secondes
      pause:
        seconds: 60

    - name: Inclure les tâches pour la gestion des plugins Jenkins
      include_tasks: "{{ deploy_path }}/deploy-ci-cd/jenkins-conf/mangerPlugins.yml"
