- name: Installer Docker, Minikube et cri-dockerd
  hosts: localhost
  become: yes
  vars:
    docker_version: "5:20.10.24~3-0~ubuntu-focal"
    minikube_version: "1.32.0"
    user_home: "/home/achref"
    user_name: "achref"

  tasks:

    - name: Installer les dépendances système
      apt:
        name:
          - curl
          - apt-transport-https
          - ca-certificates
          - software-properties-common
          - python3-pip
          - conntrack
          - socat
          - ebtables
          - iptables
        state: present

    - name: Ajouter la clé GPG Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Ajouter le dépôt Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        update_cache: yes

    - name: Installer Docker CE
      apt:
        name:
          - "docker-ce={{ docker_version }}"
          - "docker-ce-cli={{ docker_version }}"
          - containerd.io
        state: present

    - name: Redémarrer Docker
      systemd:
        name: docker
        state: restarted
        enabled: true

    - name: Ajouter l’utilisateur {{ user_name }} au groupe docker
      user:
        name: "{{ user_name }}"
        groups: docker
        append: yes

    - name: Installer le SDK Docker pour Python
      pip:
        name: docker
        executable: pip3

    - name: Télécharger et installer crictl
      block:
        - name: Télécharger crictl
          get_url:
            url: "https://github.com/kubernetes-sigs/cri-tools/releases/download/v1.28.0/crictl-v1.28.0-linux-amd64.tar.gz"
            dest: "/tmp/crictl.tar.gz"

        - name: Extraire crictl
          unarchive:
            src: "/tmp/crictl.tar.gz"
            dest: "/usr/local/bin/"
            remote_src: yes

        - name: Rendre crictl exécutable
          file:
            path: "/usr/local/bin/crictl"
            mode: '0755'
            state: file


    - name: Activer et démarrer cri-dockerd
      systemd:
        name: cri-docker
        state: started
        enabled: true

    - name: Télécharger Minikube
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/v{{ minikube_version }}/minikube-linux-amd64"
        dest: /usr/local/bin/minikube
        mode: "0755"

    - name: Démarrer Minikube avec l'utilisateur {{ user_name }}
      command: minikube start --driver=none --kubernetes-version=v1.32.0
      become: false  # Exécute la commande en tant qu'utilisateur non-root (achref)

