- name: Redirection Jenkins
  become: yes
  shell: >
    iptables-legacy -t nat -A PREROUTING -p tcp --dport {{ jenkins_nodePort }} -d {{ host_ip }} -j DNAT --to-destination {{ minikube_tunnel }}:{{ jenkins_nodePort }}

- name: Autoriser le trafic Jenkins
  become: yes
  shell: >
    iptables-legacy -A FORWARD -p tcp -d {{ minikube_tunnel }} --dport {{ jenkins_nodePort }} -j ACCEPT

- name: Redirection Nexus
  become: yes
  shell: >
    iptables-legacy -t nat -A PREROUTING -p tcp --dport {{ nexus_nodePort }} -d {{ host_ip }} -j DNAT --to-destination {{ minikube_tunnel }}:{{ nexus_nodePort }}

- name: Autoriser le trafic Nexus
  become: yes
  shell: >
    iptables-legacy -A FORWARD -p tcp -d {{ minikube_tunnel }} --dport {{ nexus_nodePort }} -j ACCEPT

- name: Redirection SonarQube
  become: yes
  shell: >
    iptables-legacy -t nat -A PREROUTING -p tcp --dport {{ sonar_nodePort }} -d {{ host_ip }} -j DNAT --to-destination {{ minikube_tunnel }}:{{ sonar_nodePort }}

- name: Autoriser le trafic SonarQube
  become: yes
  shell: >
    iptables-legacy -A FORWARD -p tcp -d {{ minikube_tunnel }} --dport {{ sonar_nodePort }} -j ACCEPT

