jenkins:
  authorizationStrategy:
    globalMatrix:
      entries:
      - userOrGroup:
          name: "admin"
          permissions:
          - "Agent/Configure"
          - "Agent/Delete"
          - "Job/Build"
          - "Job/Configure"
          - "Job/Create"
          - "Job/Delete"
          - "Job/Read"
          - "Job/Workspace"
          - "Overall/Administer"
          - "Overall/Read"
          - "Run/Delete"
          - "Run/Update"
          - "SCM/Tag"
          - "View/Configure"
          - "View/Create"
          - "View/Delete"
  clouds:
  - kubernetes:
      addMasterProxyEnvVars: true
      containerCap: 10
      containerCapStr: "10"
      jenkinsTunnel: '10.106.185.167:50000'
      jenkinsUrl: "http://192.168.100.175:30080/"
      name: "minikube"
      namespace: "jenkins"
      serverCertificate: |-
        MIIDITCCAgmgAwIBAgIBAjANBgkqhkiG9w0BAQsFADAVMRMwEQYDVQQDEwptaW5p
        a3ViZUNBMB4XDTI1MDQxMzExMjc1MloXDTI4MDQxMzExMjc1MlowMTEXMBUGA1UE
        ChMOc3lzdGVtOm1hc3RlcnMxFjAUBgNVBAMTDW1pbmlrdWJlLXVzZXIwggEiMA0G
        CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDK/B8uCTw4kiiVpF9RJBPzBofX4xKZ
        wV/D7iGYvm6eroOW5ZBbQhLfReMG61kgVRYUav+wThG8j+6RO9//WSUE1rIe6MJD
        FbiBAoVL66WA3+fzTF8ksMPmHPbgNIz6HRoP6a1JD+SEa+YkMUjEbP2OUMMeYOPD
        W0mhWkO1RPUEhfldjkxzDE5N6YOEccC/jLXFZrVLxnJf6zDFLVq7EKN1d7WmtmMV
        8b9Z4/onBTkTZTljqAn3JwY4lA5ZJ0lCZPGrjmDNLAQw6ICSVe3wfh4Hc8KUcjDR
        bJy/6zNNKh93RC0UdrRfx/qDFJQSVsfHHSElNiZvWV2iRUA8fDEwgdAHAgMBAAGj
        YDBeMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUH
        AwIwDAYDVR0TAQH/BAIwADAfBgNVHSMEGDAWgBTrpH6TAulHuRZ36PIjhqo+pb6S
        AjANBgkqhkiG9w0BAQsFAAOCAQEAJSJclyg6nuHbBSxvCOoLy7OGvq9M/sriyepd
        7r8EDXNFGRsS8A8GVm2jOBIz4KY93Uvhr9hKp2H7akMQVUoWcXPVTM6diBt1SwiA
        /QBa3AoiwHieOj1sJVQyIA4tK3ZxrfLEyi1L6q/eH04C4HLLl/t7q216gczLW4jZ
        oM1/ss5i9qOOV38CJlRowwzm0Lqw+vFCQ4uTPeUEBm4a7tYdS62PriVMU6q2loCQ
        b4PxE/QMJY+Ze2yCU+Nhgwwt9/R3mrTAMtX62j7OgEEggnZUNVekWimOKP0XoVNB
        klkfJLWY9qGkv33PiecjG06LekANjPvawPg1N3u+hA2xAbdqiQ==
      serverUrl: "192.168.100.175:8443"
      skipTlsVerify: true
      templates:
        # Template maven modifié
        - containers:
            - image: "jenkins-agent-maven:latest"
              name: "jnlp"
              args: "^${computer.jnlpmac} ^${computer.name}"
              alwaysPullImage: true
              workingDir: "/tmp"
          name: "maven"
          label: "maven"

        # Template nodejs modifié
        - containers:
            - image: "jenkins-agent-nodejs:latest"
              name: "jnlp"
              args: "^${computer.jnlpmac} ^${computer.name}"
              alwaysPullImage: true
              workingDir: "/tmp"
          name: "nodejs"
          label: "nodejs"

        # Template jnlp simplifié (nodeSelector supprimé)
        - id: "70e71f28-61f0-4168-8f76-c1cdbb44087a"
          label: "kubeagent"
          name: "jnlp"
          namespace: "jenkins"
          yaml: |-
            apiVersion: v1
            kind: Pod
            metadata:
              name: agent
              namespace: jenkins
            spec:
              containers:
                - name: jnlp
                  image: jenkins-agent-maven
                  command: ["/bin/bash", "-c"]
                  args:
                    - |
                      JENKINS_URL="^${JENKINS_URL}"
                      JENKINS_AGENT_NAME="^${JENKINS_AGENT_NAME}"
                      JENKINS_SECRET="^${JENKINS_SECRET}"
                      curl -sO "^${JENKINS_URL}/jnlpJars/agent.jar"
                      java -jar agent.jar -jnlpUrl "^${JENKINS_URL}/computer/^${JENKINS_AGENT_NAME}/jenkins-agent.jnlp" -secret "^${JENKINS_SECRET}" -noCertificateCheck
                  tty: true
                - name: docker
                  image: docker:19.03
                  command: ["sh", "-c", "sleep 9999999"]
                  securityContext:
                    privileged: true
                  volumeMounts:
                    - mountPath: /var/run/docker.sock
                      name: docker-socket
              volumes:
                - name: docker-socket
                  hostPath:
                    path: /var/run/docker.sock
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.model.BuiltInNodeMigration"
  - "hudson.util.DoubleLaunchChecker"
  labelAtoms:
  - name: "java-builder"
  - name: "kubeagent"
  - name: "master"
  - name: "maven"
  - name: "nodejs"
  - name: "nodejs-builder"
  labelString: "master"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  noUsageStatistics: true
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 5
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 1
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: true
      enableCaptcha: false
      users:
      - id: "admin"
        name: "Jenkins Admin"
        properties:
        - "consoleUrlProvider"
        - "myView"
        - mailer:
            emailAddress: "changeme@changeme.com"
        - "apiToken"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  prism:
    theme: PRISM
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  cps:
    hideSandbox: false
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  scriptApproval:
    forceSandbox: false
unclassified:
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        manageHooks: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultContentType: "text/plain"
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    watchingEnabled: false
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://192.168.100.175:30080/github-webhook/"
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://192.168.100.175:30080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  mavenModuleSet:
    localRepository: "default"
  pollSCM:
    pollingThreadCount: 10
  prometheusConfiguration:
    appendParamLabel: false
    appendStatusLabel: false
    collectCodeCoverage: false
    collectDiskUsage: true
    collectNodeStatus: true
    collectingMetricsPeriodInSeconds: 120
    countAbortedBuilds: true
    countFailedBuilds: true
    countNotBuiltBuilds: true
    countSuccessfulBuilds: true
    countUnstableBuilds: true
    defaultNamespace: "default"
    fetchTestResults: true
    jobAttributeName: "jenkins_job"
    path: "prometheus"
    perBuildMetrics: false
    processingDisabledBuilds: false
    useAuthenticatedEndpoint: false
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  sonarGlobalConfiguration:
    buildWrapperEnabled: false
    installations:
    - credentialsId: "sonar"
      name: "sonarqube"
      serverUrl: "http://192.168.100.175:30090/"
      triggers:
        skipScmCause: false
        skipUpstreamCause: false
  subversionSCM:
    workspaceFormat: 8
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"

